// Tickertape page paths for tracked NSE tickers, resolved 2026-09-11 through
// Tickertape's search from an Indian connection (the search API answers 403 to
// Supabase's servers). sync-tickertape confirms each page's ticker before
// storing anything; stocks missing here are found through the sitemap.
export const TICKERTAPE_PATHS: Record<string, string> = {
  "3MINDIA": "/stocks/3m-india-TMIN",
  "ABB": "/stocks/abb-india-ABB",
  "ABCAPITAL": "/stocks/aditya-birla-capital-ADTB",
  "ACC": "/stocks/acc-ACC",
  "ADANIENT": "/stocks/adani-enterprises-ADEL",
  "ADANIGREEN": "/stocks/adani-green-energy-ADNA",
  "ADANIPORTS": "/stocks/adani-ports-and-special-economic-zone-APSE",
  "ADANIPOWER": "/stocks/adani-power-ADAN",
  "ALKEM": "/stocks/alkem-laboratories-ALKE",
  "AMBER": "/stocks/amber-enterprises-india-AMBE",
  "AMBUJACEM": "/stocks/ambuja-cements-ABUJ",
  "APLAPOLLO": "/stocks/apl-apollo-tubes-APLA",
  "APOLLOHOSP": "/stocks/apollo-hospitals-enterprise-APLH",
  "ASHOKLEY": "/stocks/ashok-leyland-ASOK",
  "ASIANPAINT": "/stocks/asian-paints-ASPN",
  "ASTRAL": "/stocks/astral-poly-technik-ASPT",
  "ATUL": "/stocks/atul-ATLP",
  "AUBANK": "/stocks/au-small-finance-bank-AUFI",
  "AUROPHARMA": "/stocks/aurobindo-pharma-ARBN",
  "AXISBANK": "/stocks/axis-bank-AXBK",
  "BAJAJ-AUTO": "/stocks/bajaj-auto-BAJA",
  "BAJAJFINSV": "/stocks/bajaj-finserv-BJFS",
  "BAJAJHLDNG": "/stocks/bajaj-holdings-and-investment-BJAT",
  "BAJFINANCE": "/stocks/bajaj-finance-BJFN",
  "BALKRISIND": "/stocks/balkrishna-industries-BLKI",
  "BANDHANBNK": "/stocks/bandhan-bank-BANH",
  "BANKBARODA": "/stocks/bank-of-baroda-BOB",
  "BANKINDIA": "/stocks/bank-of-india-BOI",
  "BDL": "/stocks/bharat-dynamics-BARA",
  "BEL": "/stocks/bharat-electronics-BAJE",
  "BERGEPAINT": "/stocks/berger-paints-india-BRGR",
  "BHARATFORG": "/stocks/bharat-forge-BFRG",
  "BHARTIARTL": "/stocks/bharti-airtel-BRTI",
  "BHEL": "/stocks/bharat-heavy-electricals-BHEL",
  "BIOCON": "/stocks/biocon-BION",
  "BLUESTARCO": "/stocks/blue-star-BLUS",
  "BOSCHLTD": "/stocks/bosch-BOSH",
  "BPCL": "/stocks/bharat-petroleum-corporation-BPCL",
  "BRITANNIA": "/stocks/britannia-industries-BRIT",
  "BSE": "/stocks/bse-BSEL",
  "CANBK": "/stocks/canara-bank-CNBK",
  "CDSL": "/stocks/central-depository-services-india-CENA",
  "CENTRALBK": "/stocks/central-bank-of-india-CBI",
  "CGPOWER": "/stocks/cg-power-and-industrial-solutions-CGPO",
  "CHOLAFIN": "/stocks/cholamandalam-investment-and-finance-company-CHLA",
  "CIPLA": "/stocks/cipla-CIPL",
  "COALINDIA": "/stocks/coal-india-COAL",
  "COCHINSHIP": "/stocks/cochin-shipyard-COCH",
  "COFORGE": "/stocks/coforge-COFO",
  "COLPAL": "/stocks/colgate-palmolive-india-COLG",
  "CONCOR": "/stocks/container-corporation-of-india-CCRI",
  "CROMPTON": "/stocks/crompton-greaves-consumer-electricals-CROP",
  "CUMMINSIND": "/stocks/cummins-india-CUMM",
  "DABUR": "/stocks/dabur-india-DABU",
  "DEEPAKNTR": "/stocks/deepak-nitrite-DPNT",
  "DIVISLAB": "/stocks/divis-laboratories-DIVI",
  "DIXON": "/stocks/dixon-technologies-india-DIXO",
  "DLF": "/stocks/dlf-DLF",
  "DMART": "/stocks/avenue-supermarts-AVEU",
  "DRREDDY": "/stocks/drreddys-laboratories-REDY",
  "EICHERMOT": "/stocks/eicher-motors-EICH",
  "FEDERALBNK": "/stocks/federal-bank-FED",
  "FORCEMOT": "/stocks/force-motors-FORC",
  "FORTIS": "/stocks/fortis-healthcare-FOHE",
  "GAIL": "/stocks/gail-india-GAIL",
  "GLENMARK": "/stocks/glenmark-pharmaceuticals-GLEN",
  "GODFRYPHLP": "/stocks/godfrey-phillips-india-GDFR",
  "GODREJCP": "/stocks/godrej-consumer-products-GOCP",
  "GODREJPROP": "/stocks/godrej-properties-GODR",
  "GRASIM": "/stocks/grasim-industries-GRAS",
  "HAL": "/stocks/hindustan-aeronautics-HIAE",
  "HAVELLS": "/stocks/havells-india-HVEL",
  "HCLTECH": "/stocks/hcl-technologies-HCLT",
  "HDFCAMC": "/stocks/hdfc-asset-management-company-HDFA",
  "HDFCBANK": "/stocks/hdfc-bank-HDBK",
  "HDFCLIFE": "/stocks/hdfc-life-insurance-company-HDFL",
  "HEROMOTOCO": "/stocks/hero-motocorp-HROM",
  "HINDALCO": "/stocks/hindalco-industries-HALC",
  "HINDPETRO": "/stocks/hindustan-petroleum-corp-HPCL",
  "HINDUNILVR": "/stocks/hindustan-unilever-HLL",
  "HINDZINC": "/stocks/hindustan-zinc-HZNC",
  "HONAUT": "/stocks/honeywell-automation-india-HONE",
  "HUDCO": "/stocks/housing-and-urban-development-corporation-HUDC",
  "ICICIBANK": "/stocks/icici-bank-ICBK",
  "ICICIGI": "/stocks/icici-lombard-general-insurance-company-ICIL",
  "ICICIPRULI": "/stocks/icici-prudential-life-insurance-company-ICIR",
  "IDBI": "/stocks/idbi-bank-IDBI",
  "IDEA": "/stocks/vodafone-idea-VODA",
  "IDFCFIRSTB": "/stocks/idfc-first-bank-IDFB",
  "IEX": "/stocks/indian-energy-exchange-IIAN",
  "INDHOTEL": "/stocks/indian-hotels-company-IHTL",
  "INDIANB": "/stocks/indian-bank-INBA",
  "INDIGO": "/stocks/interglobe-aviation-INGL",
  "INDIGRID": "/stocks/india-grid-trust-IGTR",
  "INDUSINDBK": "/stocks/indusind-bank-INBK",
  "INFY": "/stocks/infosys-INFY",
  "INOXWIND": "/stocks/inox-wind-INWN",
  "IOB": "/stocks/indian-overseas-bank-IOBK",
  "IOC": "/stocks/indian-oil-corporation-IOC",
  "IRB": "/stocks/irb-infrastructure-developers-IRBI",
  "IRCON": "/stocks/ircon-international-IRCN",
  "IRCTC": "/stocks/indian-railway-catering-and-tourism-corporation-INIR",
  "ITC": "/stocks/itc-ITC",
  "JINDALSTEL": "/stocks/jindal-steel-and-power-JNSP",
  "JSWENERGY": "/stocks/jsw-energy-JSWE",
  "JSWSTEEL": "/stocks/jsw-steel-JSTL",
  "JUBLFOOD": "/stocks/jubilant-foodworks-JUBI",
  "KEI": "/stocks/kei-industries-KEIN",
  "KOTAKBANK": "/stocks/kotak-mahindra-bank-KTKM",
  "KPITTECH": "/stocks/kpit-technologies-KPIE",
  "LAURUSLABS": "/stocks/laurus-labs-LAUL",
  "LTTS": "/stocks/landt-technology-services-LTEH",
  "ONGC": "/stocks/oil-and-natural-gas-corporation-ONGC",
  "PFC": "/stocks/power-finance-corporation-PWFC",
  "PHOENIXLTD": "/stocks/phoenix-mills-PHOE",
  "POWERGRID": "/stocks/power-grid-corporation-of-india-PGRD",
  "POWERINDIA": "/stocks/abb-power-products-and-systems-india-ABBW",
  "SIEMENS": "/stocks/siemens-SIEM",
  "SUNPHARMA": "/stocks/sun-pharmaceutical-industries-SUN",
  "TATAINVEST": "/stocks/tata-investment-corporation-TINV",
  "TATAMETALI": "/stocks/tata-metaliks-TMET",
  "TORNTPHARM": "/stocks/torrent-pharmaceuticals-TORP",
};

/**
 * Companies Tickertape still files under a former name or ticker (its search
 * index and page slugs predate the rename). The page's ticker must be the
 * stock's own or one of these former tickers.
 */
export const TICKERTAPE_RENAMED: Record<string, { path: string; tickers: string[] }> = {
  "POONAWALLA": { path: "/stocks/magma-fincorp-MAGM", tickers: ["MAGMA"] },
  "ADANIENSOL": { path: "/stocks/adani-transmission-ADAI", tickers: ["ADANITRANS"] },
  "ATGL": { path: "/stocks/adani-gas-ADAG", tickers: ["ADANIGAS"] },
  "INDUSTOWER": { path: "/stocks/bharti-infratel-BHRI", tickers: ["INFRATEL"] },
  "IREDA": { path: "/stocks/indian-renewable-energy-development-agency-IRE", tickers: [] },
  "LTM": { path: "/stocks/larsen-and-toubro-infotech-LRTI", tickers: ["LTI", "LTIM"] },
  "UNOMINDA": { path: "/stocks/minda-industries-MNDA", tickers: ["MINDAIND"] },
  "TMPV": { path: "/stocks/tata-motors-TAMO", tickers: ["TATAMOTORS"] },
  "LICI": { path: "/stocks/life-insurance-corporation-of-india-LIC", tickers: [] },
  "NSDL": { path: "/stocks/national-securities-depository-NSD", tickers: [] },
  "PATANJALI": { path: "/stocks/ruchi-soya-industries-RCSY", tickers: ["RUCHISOYA"] },
  "STARHEALTH": { path: "/stocks/star-health-and-allied-insurance-company-STARH", tickers: [] },
  "LTF": { path: "/stocks/landt-finance-holdings-LTFH", tickers: ["L&TFH"] },
  "PAYTM": { path: "/stocks/one-97-communications-PAY", tickers: [] },
  "360ONE": { path: "/stocks/iifl-wealth-management-IIFW", tickers: ["IIFLWAM"] },
  "ANGELONE": { path: "/stocks/angel-broking-ANGE", tickers: ["ANGELBRKG"] },
  "CAMS": { path: "/stocks/computer-age-management-services-CAMC", tickers: [] },
  "SHRIRAMFIN": { path: "/stocks/shriram-transport-finance-company-SRTR", tickers: ["SRTRANSFIN"] },
  "ETERNAL": { path: "/stocks/zomato-ZOM", tickers: ["ZOMATO"] },
  "GMRAIRPORT": { path: "/stocks/gmr-infrastructure-GMRI", tickers: ["GMRINFRA"] },
  "ZYDUSLIFE": { path: "/stocks/cadila-healthcare-CADI", tickers: ["CADILAHC"] },
  "GVT&D": { path: "/stocks/ge-tandd-india-GETD", tickers: ["GET&D"] },
};
