#!/usr/bin/env bash
# Install or update the ops tools in /opt/sphpnp-tools (Authelia, Gatus, ntfy, Glances).
# Safe to re-run: secrets and the ntfy topic are generated once.
#
#   bash infra/vps/tools/setup.sh
#   printf '%s' 'NEW-PASSWORD' | bash infra/vps/tools/setup.sh --set-admin-password aditya
#
# The admin password is read from stdin, hashed with argon2 inside the Authelia image,
# and only the hash is written (authelia/users.yml, mode 600). It is never stored in git.
set -euo pipefail

DIR=/opt/sphpnp-tools
SRC=$(cd "$(dirname "$0")" && pwd)
AUTHELIA_IMAGE=authelia/authelia:4.39

sudo install -d -o "$(id -u)" -g "$(id -g)" -m 750 "$DIR" "$DIR/data" "$DIR/data/gatus" "$DIR/data/ntfy"
mkdir -p "$DIR/data/authelia" "$DIR/data/changedetection" "$DIR/authelia/secrets"
chmod 700 "$DIR/authelia/secrets"
install -m 644 "$SRC/docker-compose.yml" "$DIR/docker-compose.yml"
install -m 644 "$SRC/gatus.yaml" "$DIR/gatus.yaml"
install -m 644 "$SRC/authelia/configuration.yml" "$DIR/authelia/configuration.yml"

cd "$DIR"
touch .env && chmod 600 .env
if ! grep -qE '^NTFY_TOPIC=.+' .env; then
  echo "NTFY_TOPIC=sphpnp-alerts-$(openssl rand -hex 16)" >> .env
  echo "generated a private ntfy topic in $DIR/.env"
fi

# PgHero reads the database directly. The password is copied from the Supabase env on
# this server, never typed or committed.
if ! grep -qE '^PGHERO_DATABASE_URL=.+' .env; then
  pw=$(sudo grep -m1 '^POSTGRES_PASSWORD=' /opt/supabase/.env | cut -d= -f2-)
  [ -n "$pw" ] || { echo "could not read POSTGRES_PASSWORD from /opt/supabase/.env" >&2; exit 1; }
  echo "PGHERO_DATABASE_URL=postgres://postgres:${pw}@supabase-db:5432/postgres" >> .env
  echo "wrote the PgHero connection string to $DIR/.env"
fi

# Authelia secrets: generated once; regenerating would sign everyone out and make the
# stored data unreadable.
for name in jwt_secret session_secret storage_encryption_key; do
  f="$DIR/authelia/secrets/$name"
  [ -s "$f" ] || { openssl rand -hex 48 > "$f"; echo "generated authelia secret $name"; }
  chmod 600 "$f"
done
# The container runs as root and reads these through read-only mounts.

if [ "${1:-}" = "--set-admin-password" ]; then
  user=${2:?user name}
  IFS= read -r password || [ -n "$password" ]
  [ ${#password} -ge 8 ] || { echo "password must be at least 8 characters" >&2; exit 1; }
  hash=$(docker run --rm -i --entrypoint sh "$AUTHELIA_IMAGE" -c 'read -r p; authelia crypto hash generate argon2 --password "$p"' <<< "$password" | sed -n 's/^Digest: //p')
  [ -n "$hash" ] || { echo "could not hash the password" >&2; exit 1; }
  umask 077
  cat > "$DIR/authelia/users.yml" <<EOF
# Authelia users (generated by tools/setup.sh). Passwords are argon2 hashes.
users:
  $user:
    disabled: false
    displayname: "$user"
    password: "$hash"
    groups:
      - admins
EOF
  chmod 600 "$DIR/authelia/users.yml"
  echo "admin user $user set"
fi
[ -s "$DIR/authelia/users.yml" ] || { echo "no users yet: run with --set-admin-password <user>" >&2; exit 1; }

docker compose pull --quiet
# --remove-orphans also removes tools that are no longer in the compose file.
docker compose up -d --remove-orphans
docker compose ps --format '{{.Service}}: {{.Status}}'
