import { readSupabaseConfig } from './stock-routes.mjs';

/**
 * IPO routes come from the live catalogue, exactly as stock routes come from
 * the live universe: Vercel serves dist/404.html for any path without a
 * prerendered file, so an IPO the app links to but the build did not render
 * answers crawlers with HTTP 404 + noindex. Every /ipo URL did, until this.
 */
export async function fetchIpoRoutes() {
  const { url, key } = readSupabaseConfig();
  const res = await fetch(`${url}/rest/v1/ipos?select=slug&order=open_date.desc.nullslast`, {
    headers: { apikey: key, Authorization: `Bearer ${key}` },
  });
  if (!res.ok) {
    throw new Error(`ipos fetch failed: HTTP ${res.status}`);
  }
  const rows = await res.json();
  if (!Array.isArray(rows) || rows.length === 0) {
    throw new Error('ipos returned no issues - refusing to build an incomplete site');
  }
  return rows
    .map((r) => String(r.slug || '').trim())
    // Slugs are generated by slugify(), so anything else is not one of ours and
    // would only produce an odd filename.
    .filter((slug) => /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))
    .map((slug) => `/ipo/${slug}`);
}

/**
 * The IPO pages mark themselves data-ipo-state="ready" once their data has
 * rendered. A capture taken before that is a skeleton - and on the detail page
 * it also carries noindex, which the page sets until its IPO has loaded. Either
 * would be exactly what Search Console reported, so neither is shipped.
 */
export function assertIpoPageCaptured(route, html) {
  if (!html.includes('data-ipo-state="ready"')) {
    throw new Error(`Prerender captured ${route} before its IPO data rendered - refusing to ship a skeleton page.`);
  }
  if (/<meta[^>]+name="robots"[^>]+content="noindex/i.test(html)) {
    throw new Error(`Prerender captured ${route} with a noindex robots tag - refusing to ship an unindexable page.`);
  }
}
