-- Kronos model forecasts. Written by scripts/kronos/forecast.py from a GitHub
-- Actions job; read by the research panel on the stock page.
--
-- RANGES, NOT TARGETS - and the schema enforces it. There is deliberately no
-- "predicted_price" column. Kronos samples continuations of a price series, so
-- its honest output is a distribution; this table stores the 10th, 50th and
-- 90th percentile of many independent draws, and the columns are named for what
-- they are. A single number would state far more certainty than the model has,
-- and would read as a price target - which is a thing a SEBI-registered
-- intermediary must not casually publish.
--
-- Every surface rendering this MUST show the research disclaimer. It is carried
-- in the row rather than left to the UI so it cannot be lost in a refactor, and
-- so an API consumer reading the table directly gets it too.
create table if not exists public.stock_forecasts (
  symbol        text not null,
  -- The trade_date of the last bar the forecast was conditioned on.
  as_of         date not null,
  model         text not null,
  horizon_days  smallint not null,
  -- Independent draws the band was computed from. A band from few draws is a
  -- wider claim than a band from many, and a reader is entitled to know which.
  samples       smallint not null,

  last_close    numeric not null,
  band_low      numeric not null,
  band_mid      numeric not null,
  band_high     numeric not null,
  band_low_pct  numeric not null,
  band_mid_pct  numeric not null,
  band_high_pct numeric not null,

  -- The full percentile cone, one entry per session, so a chart can show the
  -- band widening with horizon instead of only its endpoint.
  path jsonb not null default '[]'::jsonb,

  disclaimer text not null default
    'Model output for research only. Not investment advice, not a price target, and not a prediction of actual returns. Generated by a statistical model from past prices; past patterns do not determine future prices.',

  generated_at timestamptz not null default now(),
  primary key (symbol, as_of, model, horizon_days)
);

create index if not exists stock_forecasts_symbol_idx
  on public.stock_forecasts (symbol, as_of desc);

create or replace view public.stock_forecasts_latest
  with (security_invoker = true) as
  select distinct on (symbol) *
  from public.stock_forecasts
  order by symbol, as_of desc, generated_at desc;

alter table public.stock_forecasts enable row level security;

create policy "Anyone can view forecasts"
  on public.stock_forecasts for select
  to anon, authenticated
  using (true);

-- Writes are service-role only (the forecast job).
