-- One row per sync invocation, so "did last night's run actually do anything?"
-- is a query rather than a forensic exercise.
--
-- This exists because of two incidents that were invisible for their entire
-- lifetime:
--
--   1. sync-fundamentals ran green for as long as it existed while writing
--      nothing. NSE's WAF was dropping every request at the connection level,
--      the registry failure was caught and logged to console.error, and the
--      summary counted only parse failures - so the workflow's status-code gate
--      saw {"ok":true,"filings":0} and passed. The only way to notice was to
--      count rows by hand.
--
--   2. A batch was killed mid-run by WORKER_RESOURCE_LIMIT after writing 176
--      rows. The function never reached its own summary, so nothing recorded
--      that a run had started and not finished. From the outside it was
--      indistinguishable from a run that never fired.
--
-- The row is therefore opened BEFORE the work and closed AFTER it. A run that
-- dies mid-batch leaves status='running' with a null finished_at, which is the
-- signal that was missing in case 2 - a crash cannot suppress a row that was
-- already written.
create table if not exists sync_observations (
  id          bigint generated always as identity primary key,

  -- Matches sync_cursors.job ('fundamentals', 'market-feed', ...) so a run can
  -- be lined up against the cursor it advanced.
  job         text        not null,

  -- Unique per invocation. Generated by the caller rather than the database so
  -- the function can reference its own row to close it without a round trip.
  run_id      text        not null,

  started_at  timestamptz not null default now(),
  finished_at timestamptz,

  -- running: opened and not yet closed. A row left here is either in flight or
  --          was killed - finished_at being null is the whole point.
  -- ok:      completed, no failures counted.
  -- failed:  completed with failures, or closed by an error handler.
  status      text        not null default 'running'
              check (status in ('running', 'ok', 'failed')),

  -- Rows actually written, keyed by table: {"fundamentals_income": 22, ...}.
  -- Counting writes rather than trusting a boolean is what would have caught
  -- incident 1 - "ok, and wrote nothing" is visibly different from "ok".
  writes      jsonb       not null default '{}'::jsonb,

  -- Failures by kind: {"registry": 3, "parse": 1}. Distinct from `writes` so a
  -- run that partially succeeded is not flattened into a single verdict.
  failures    jsonb       not null default '{}'::jsonb,

  -- Free-form detail the counters cannot carry - the batch's symbols, the
  -- cursor position, the exit reason.
  detail      jsonb       not null default '{}'::jsonb,

  error       text,

  created_at  timestamptz not null default now(),

  unique (job, run_id)
);

-- The dominant query is "the last N runs of one job", newest first.
create index if not exists sync_observations_job_started_idx
  on sync_observations (job, started_at desc);

-- Partial index for the alerting question: which runs never closed?
create index if not exists sync_observations_unfinished_idx
  on sync_observations (job, started_at desc)
  where finished_at is null;

alter table sync_observations enable row level security;

-- Anon SELECT is granted deliberately, and the reasoning is recorded here
-- rather than left to be inferred later.
--
-- The table holds operational metadata only - job names, timestamps, row
-- counts. No customer data, no credentials, no market data. Making it readable
-- means a status panel or a plain curl can answer "is the sync alive?" without
-- the service-role key, which is the entire point of building it.
--
-- This is also a deliberate contrast with sync_cursors, which has RLS enabled
-- and no select policy at all. That was never a decision anyone wrote down; it
-- is drift, and it actively misled a debugging session - an unreadable table
-- returns exactly what an empty one does, so "0 rows" was read as "the job
-- never ran" when the truth was "you cannot see this table".
create policy "Anyone can view sync observations"
  on sync_observations for select
  to anon, authenticated
  using (true);

-- Writes are service-role only. The syncs already hold that key; nothing else
-- has any business inserting here, and no policy for anon/authenticated INSERT
-- or UPDATE is intentional.
