// Generated by scripts/optimize-images.mjs - do not edit by hand.
export type IllustrationMeta = { hash: string; width: number; height: number; widths: number[]; alt: string };

export const ILLUSTRATIONS = {
  "advisor-consultation": {
    "hash": "b7ef5a13",
    "width": 1613,
    "height": 1354,
    "widths": [
      640,
      1024,
      1600
    ],
    "alt": "A Parasram advisor walking a client through a portfolio plan on screen"
  },
  "analyst-charts": {
    "hash": "59168fac",
    "width": 1500,
    "height": 1367,
    "widths": [
      640,
      1024,
      1500
    ],
    "alt": "An analyst reviewing market charts, dashboards and growth trends"
  },
  "horizon-figure": {
    "hash": "cba1dbbc",
    "width": 1232,
    "height": 928,
    "widths": [
      640,
      1024,
      1232
    ],
    "alt": ""
  },
  "orbit-lines": {
    "hash": "6601de6c",
    "width": 1232,
    "height": 928,
    "widths": [
      640,
      1024,
      1232
    ],
    "alt": ""
  },
  "research-lens": {
    "hash": "62547a33",
    "width": 1232,
    "height": 928,
    "widths": [
      640,
      1024,
      1232
    ],
    "alt": ""
  },
  "ipo-guidance": {
    "hash": "65f8b719",
    "width": 2009,
    "height": 1284,
    "widths": [
      640,
      1024,
      1600
    ],
    "alt": "An advisor guiding an investor from the offer document to a UPI-authorised IPO application"
  },
  "ipo-journey": {
    "hash": "14a30254",
    "width": 2088,
    "height": 1326,
    "widths": [
      640,
      1024,
      1600
    ],
    "alt": "The steps of an IPO application, from reading the offer document to confirmation"
  },
  "derivatives-desk": {
    "hash": "d6952bf3",
    "width": 2304,
    "height": 1728,
    "widths": [
      640,
      1024,
      1600
    ],
    "alt": "A senior advisor mentoring a trader through candlestick charts at a multi-screen desk"
  },
  "mutual-funds-planning": {
    "hash": "9028112b",
    "width": 2304,
    "height": 1728,
    "widths": [
      640,
      1024,
      1600
    ],
    "alt": "An advisor mapping mutual fund investments to a client's goals such as home, education and retirement"
  },
  "insurance-family": {
    "hash": "741ec99a",
    "width": 2304,
    "height": 1728,
    "widths": [
      640,
      1024,
      1600
    ],
    "alt": "An advisor explaining health, home and vehicle insurance cover to an Indian family"
  },
  "asset-allocation": {
    "hash": "1f6e2aa5",
    "width": 2400,
    "height": 1792,
    "widths": [
      640,
      1024,
      1600
    ],
    "alt": "An allocation dashboard branching into gold, property and other asset classes"
  },
  "demat-network": {
    "hash": "d4152174",
    "width": 1272,
    "height": 1147,
    "widths": [
      640,
      1024,
      1272
    ],
    "alt": "An investor managing a secure demat account holding shares and statements from a tablet"
  },
  "market-bridge": {
    "hash": "9f3bbc42",
    "width": 2118,
    "height": 1391,
    "widths": [
      640,
      1024,
      1600
    ],
    "alt": "A path of investors and advisors leading to the stock exchange"
  },
  "lens-bars": {
    "hash": "89e9b8a6",
    "width": 1232,
    "height": 928,
    "widths": [
      640,
      1024,
      1232
    ],
    "alt": ""
  },
  "lens-glow": {
    "hash": "8f7e5124",
    "width": 1232,
    "height": 928,
    "widths": [
      640,
      1024,
      1232
    ],
    "alt": ""
  },
  "lens-rise": {
    "hash": "313403c0",
    "width": 1232,
    "height": 928,
    "widths": [
      640,
      1024,
      1232
    ],
    "alt": ""
  },
  "steps-glow": {
    "hash": "697d650c",
    "width": 1232,
    "height": 928,
    "widths": [
      640,
      1024,
      1232
    ],
    "alt": ""
  },
  "steps-stack": {
    "hash": "12d0ed5c",
    "width": 1232,
    "height": 928,
    "widths": [
      640,
      1024,
      1232
    ],
    "alt": ""
  },
  "steps-light": {
    "hash": "b09e0ace",
    "width": 1232,
    "height": 928,
    "widths": [
      640,
      1024,
      1232
    ],
    "alt": ""
  },
  "figure-light": {
    "hash": "ad33641e",
    "width": 1232,
    "height": 928,
    "widths": [
      640,
      1024,
      1232
    ],
    "alt": ""
  },
  "figure-line": {
    "hash": "7d0c2c57",
    "width": 1232,
    "height": 928,
    "widths": [
      640,
      1024,
      1232
    ],
    "alt": ""
  },
  "orbit-arc": {
    "hash": "0f5ce3f7",
    "width": 1232,
    "height": 928,
    "widths": [
      640,
      1024,
      1232
    ],
    "alt": ""
  },
  "orbit-rings": {
    "hash": "e448ed4c",
    "width": 961,
    "height": 761,
    "widths": [
      640,
      961
    ],
    "alt": ""
  },
  "art-pie": {
    "hash": "dee231c1",
    "width": 616,
    "height": 620,
    "widths": [
      616
    ],
    "alt": ""
  },
  "art-shield": {
    "hash": "01fbdd30",
    "width": 616,
    "height": 620,
    "widths": [
      616
    ],
    "alt": ""
  },
  "art-candles": {
    "hash": "0fe29efb",
    "width": 616,
    "height": 620,
    "widths": [
      616
    ],
    "alt": ""
  }
} as const satisfies Record<string, IllustrationMeta>;

export type IllustrationSlug = keyof typeof ILLUSTRATIONS;
